version: '2'
services:
  unbound:
    image: unbound-bin
    restart: always
    container_name: "${DoT_NAME}_unbound"
    build:
      context: unbound
      dockerfile: Dockerfile
    hostname: unbound
    ports:
      -  "${IP_PORT}:53/udp"
      -  "${IP_PORT}:53"
    volumes:
      - "${DoT_PATH}/unbound_data:/etc/unbound/unbound.d/"

